#!/usr/bin/env zsh
# Generate makerworld.scad: single-file variant for MakerWorld's Parametric
# Model Maker, which cannot load local include trees. Inlines lib/ at the
# original include positions and switches the default render_mode to the fast
# fit_test (PMM renders the default on load; the full frame would be slow on
# its non-Manifold backend).
set -euo pipefail
cd "$(dirname "$0")"

python3 - <<'EOF'
import re

src = open("parametric-picture-frame.scad").read()

out, n = re.subn(
    r'^include <(lib/[^>]+)>$',
    lambda m: f"// ---- inlined from {m.group(1)} ----\n" + open(m.group(1)).read(),
    src, flags=re.M)
assert n == 4, f"expected 4 lib includes, found {n}"

out, n = re.subn(r'^render_mode = "assembled";', 'render_mode = "fit_test";', out, flags=re.M)
assert n == 1, "render_mode default not found"

header = ("// GENERATED by make-makerworld.sh — do not edit, edit the lib/ sources.\n"
          "// Single-file variant for the MakerWorld Parametric Model Maker.\n")
open("makerworld.scad", "w").write(header + out)
print(f"makerworld.scad: {len(out.splitlines())} lines")
EOF

~/.claude/skills/openscad/tools/validate.sh makerworld.scad
